version: '3.8'

x-common: &x-common
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  env_file:
    - .env
  volumes:
    - ./docker:/app
    - ./beatmaps:/beatmaps
    - ./sql:/sql
  build:
    context: ./docker
    dockerfile: Dockerfile

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/mysql
      - ./db:/etc/mysql/conf.d
    ports:
      - "33306:3306"
    command: ['--innodb-buffer-pool-size=${INNODB_BUFFER_SIZE}']

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  importer:
    <<: *x-common
    working_dir: '/app/importer'
    command: [ './import.sh' ]

  diffcalc:
    <<: *x-common
    working_dir: '/app/diffcalc'
    command: [ './start.sh' ]

  ppcalc:
    <<: *x-common
    working_dir: '/app/ppcalc'
    command: [ './start.sh' ]

  generator:
    <<: *x-common
    working_dir: '/app/generator'
    volumes:
      - ./docker:/app
      - ${GOOGLE_CREDENTIALS_FILE}:/credentials.json
    command: [ './start.sh' ]

volumes:
  database: